### PR TITLE
Multi package

### PR DESCRIPTION
**Pull request by behrisch**
allow running for multiple packages without re-entering credentials

### CODE REVIEW

**Comment by arcivanov** [comment]
Thanks for your PR. This needs to be thought through more thoroughly.
If batching is desired some packages may not be authorized for the user to delete while others will be.
The current behavior will be fail-on-first.

**Comment by behrisch** [comment]
Yes, that was intended. There may be other things which go wrong (typo in package name etc.) so I wanted to stop as soon as the first error occurs to give immediate feedback and not to hide the error with subsequent success messages. Feel free to change it though :-)

**Comment by arcivanov** [comment]
So when I'm thinking "batch action" I'm thinking what `git` does when you delete multiple branches.

```
$ git branch -d a b c
error: branch 'a' not found.
error: branch 'b' not found.
error: branch 'c' not found.
```

Unless there is a rush, I'd like to think about it a bit.

**Comment by behrisch** [comment]
no rush at all, I am working with my own branch and like your approach just as well.

**Comment by arcivanov** [comment]
Thanks for the PR, but since the code has diverged it was easier to implement my own changes for this one.
Thanks again!

**Pull request closed without merging**
